services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    networks:
      - jenkins-network
    command: --storage-driver overlay2
    healthcheck:
      test: ["CMD-SHELL", "docker info || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # Increased to allow dind to initialize

  jenkins-server:
    build: .  # Build the image from the Dockerfile in the current directory
    container_name: jenkins-server
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://jenkins-docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins-network
    depends_on:
      jenkins-docker:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # Allow Jenkins to initialize

  jenkins-agent:
    image: jenkins/inbound-agent:latest-jdk17
    container_name: jenkins-agent
    networks:
      - jenkins-network
    restart: always
    volumes:
      - docker-agent_data:/home/jenkins/agent
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JENKINS_URL=http://jenkins-server:8080
      - JENKINS_SECRET=f0104c378a80d45110b8ffca8e9a7fd74dcef82d7de55cee396a103c8399f9fe  ##Check the secret code
      - JENKINS_AGENT_NAME=jenkins-agent
    user: root
    privileged: true
    depends_on:
      jenkins-server:
        condition: service_healthy

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins-docker-certs:
  jenkins-data:
  docker-agent_data:
